require("hyprland/keybinds")
require("hyprland/animations")
require("hyprland/general")
require("hyprland/monitors")
require("hyprland/autostart")
require("hyprland/layouts")
require("hyprland/window_rules")
require("hyprland/env")
